package entidad.bancaria.cuentas;

public enum MotivoDeTransaccion {
	
	DEPOSITO_POR_VENTANILLA,
	EXTRACCION_POR_VENTANILLA,
	TRANSFERENCIA,
	PAGO_DE_INTERES,
	RETENCION_DE_IMPUESTOS,
	COBRO_DE_MANTENIMIENTO, 
	DEPOSITO_INICIAL;

}
